codecov:
  require_ci_to_pass: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
  require_base: yes        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "master"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "api/src"
          - "core/src"
          - "admin/src
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
  notify:
    slack:
      default:
        url: secret:GHCw96lMvGW8IUwkrnNJyhNaUbmT2jZMvalmEibVBe+EPokNYSvMAPzwk9hO7MVpd7w9GH1GUXbe7hEk5xNDT+4mDlP1lOs76J+uUuW4TVVkAyCEXZDI3HzjWBbKmqKk1zspq484LZvJOvYMm1lj64PfW5kvkGrTumYS7XuJmmc=
        threshold: 1%
        only_pulls: false
        branches: 
          - "master"
        flags: 
          - "unit"
        paths: 
          - "api/src"
          - "core/src"
          - "admin/src"
