spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaonna
    username: gaonna
    password: gaonna
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
