spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gaonna
    username: gaonna
    password: gaonna
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: create-drop
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: ENC(OtjU1nTEX4FPdzuPzLic+CuvtqbjVZ9RWZqAOof5jbw=)
            clientSecret: ENC(pSp2Ylut6QM+xRGvWlktpkbhUZcw2EuL)
            client-name: Naver
            scope: profile
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
          kakao:
            clientId: c1991c38f4f71873ec0e76c9106348af
            clientSecret: V6pHGRoDBWDTSIKqFrGyORfvgAt4KCNz
            client-authentication-method: post
            client-name: Kakao
            scope: 'account_email,profile_image,profile_nickname'
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
bbolab:
  fileservice:
    root: "./"

security:
  auth:
    tokenSecret: ENC(4TvrXQOxQ0CaSWzuhzi41DagljfpCp7GOnGFMok4lj0=)
    accessTokenExpireTime: 1800000
    refreshTokenExpireTime: 1209600000

  oauth2:
    authorizedRedirectUris:
#      - http://localhost:8080/oauth2/redirect

logging:
  level:
    root: info

jasypt:
  encryptor:
    password: ${GAONNA_KEY}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
