spring:
  datasource:
    url: ENC(kjTdWiAZqGMAPc+Rb4Y6nar1nYJwdJcQBaOzDAAziA7cKuBPZAJQMGKSqXdxaAfA)
    username: ENC(j3UQH7kUdtWZIXmTVjne+w==)
    password: ENC(qa8Ir8x2zAUzQ86x/l1jvm2F1Jylwjh7yGdw4oUsTF9Vl0SWj3xvIACzutaWCFYq)
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: ENC(xDjTR1GVmbcH56P8XA7hiGpk64kiJ1/ZTszVJgT6Wow=)
            clientSecret: ENC(4RR6sPvkzeAikoT1s2wELIIXug95eR6O)
            client-name: Naver
            scope: profile
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
          kakao:
            clientId: ENC(HL2Th6D23icsT/c8i6oH0fj490jIw+Fiq5NRAa/7wLVoK4BayPKJoOdEeCc9R62O)
            clientSecret: ENC(cPjTN22EW+W1ESyGxRfNRh84TOca9EAOXoVEQBYpTNSxEFTmuTc8Ydx6tbNj/sK9)
            client-authentication-method: post
            client-name: Kakao
            scope: 'account_email,profile_image,profile_nickname'
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

security:
  auth:
    tokenSecret: ENC(4TvrXQOxQ0CaSWzuhzi41DagljfpCp7GOnGFMok4lj0=)
    accessTokenExpireTime: 1800000
    refreshTokenExpireTime: 1209600000

  oauth2:
    authorizedRedirectUris:
#      - http://localhost:8080/oauth2/redirect

jasypt:
  encryptor:
    password: ${GAONNA_KEY}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
