spring:
  datasource:
    url: ENC(j2kYv3PPxmqE5P7fWoPOLnUOl0XAy6nQyErmbOOhPiVckV1lARbdU2Xg+0CnIsCG)
    username: ENC(zi/h8lhp032KDZsjn4u/vg==)
    password: ENC(nmwjNDwdJrkRhKF0hMB3n2TkdI2cX4ZaAPnRF/vawY9m44ciOqJ9lVUUxi01ETsb)
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: ENC(OtjU1nTEX4FPdzuPzLic+CuvtqbjVZ9RWZqAOof5jbw=)
            clientSecret: ENC(pSp2Ylut6QM+xRGvWlktpkbhUZcw2EuL)
            client-name: Naver
            scope: profile
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

security:
  auth:
    tokenSecret: ENC(4TvrXQOxQ0CaSWzuhzi41DagljfpCp7GOnGFMok4lj0=)
    accessTokenExpireTime: 1800000
    refreshTokenExpireTime: 1209600000

  oauth2:
    authorizedRedirectUris:
#      - http://localhost:8080/oauth2/redirect

jasypt:
  encryptor:
    password: ${GAONNA_KEY}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
