spring:
  datasource:
    url: ENC(UhgbcqG/9hAI1V+ZdgopcQTSmGj6JYFvsZOWCRP2K0D/DzFpk1D9FQ==)
    username: ENC(zi/h8lhp032KDZsjn4u/vg==)
    password: ENC(V9KsgC6+ur5Udc419y+VyecaGIWXB6oKRjWsO7VEcCUyFI0Y+S5qJJUXBHP6m2Ch)
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
jasypt:
  encryptor:
    password: ${GAONNA_KEY}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
