server:
  port: 9300
spring:
  datasource:
    url: ENC(j2kYv3PPxmqE5P7fWoPOLnUOl0XAy6nQyErmbOOhPiVckV1lARbdU2Xg+0CnIsCG)
    username: ENC(j3UQH7kUdtWZIXmTVjne+w==)
    password: ENC(nmwjNDwdJrkRhKF0hMB3n2TkdI2cX4ZaAPnRF/vawY9m44ciOqJ9lVUUxi01ETsb)
jasypt:
  encryptor:
    password: ${GAONNA_KEY}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
