#!groovy

pipeline {
    agent any
    tools {
        jdk 'openjdk-11'
    }
    stages{
        stage('Git Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Gradlew Build'){
            steps{
                script{
                    sh """
                    echo ${CHANGE_TARGET}
                    echo ${GITHUB_PR_STATE}
                    chmod +x ./gradlew
                    ./gradlew build
                    """
                }
            }
        }
        stage('Test'){
            steps{
                script{
                    sh "./gradlew test"
                    sh "./gradlew check"
                    sh "echo 'generating coverage report'"
                    sh "./gradlew codeCoverageReport"
                    sh "echo 'send it to codecov'"
                    sh "curl -s https://codecov.io/bash | bash"
                }
            }
        }
        stage('Push image to Harbor'){
            when{
                allOf {
                    expression { env.GITHUB_PR_STATE == "CLOSE"};
                    branch 'master';
                }
            }
            steps{
                sh """
                ./gradlew jib -PHARBOR_USERNAME="${HARBOR_USERNAME}" -PHARBOR_PASSWORD="${HARBOR_PASSWORD}" -PDOCKER_IMG_BASE_REPOSITORY="${DOCKER_IMG_BASE_REPOSITORY}" -PHARBOR_REPOSITORY="${HARBOR_REPOSITORY}" -PIMG_TAG="${BUILD_NUMBER}"
                """
            }
        }
    }
}
