#!groovy

pipeline {
    agent any
    tools {
        jdk 'openjdk-11'
    }
    stages{
        stage('Git Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Gradlew Build'){
            steps{
                script{
                    sh """
                    chmod +x ./gradlew
                    ./gradlew build
                    """
                }
            }
        }
        stage('Test'){
            steps{
                script{
                    sh "./gradlew test"
                }
            }
        }
    }
}
